[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public" # ganti jika kamu pakai Next.js (biasanya ".next" atau "out")

[dev]
  functions = "netlify/functions"
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
