[build]
  command = "npm run build"
  publish = ".next" # jika pakai Next.js
  functions = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_URL = "https://dogepoi.netlify.app"
  MY_URL = "https://dogepoi.netlify.app"
  PROXY = "https://my-proxy-production.up.railway.app"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
